In [1]:
import numpy as np


# resize and reshape

In [3]:
simple_array = np.arange(0,12)

In [4]:
print(simple_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
print(simple_array.size)

12


In [9]:
print(np.resize(simple_array,(3,4)))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print(np.resize(simple_array,(4,5)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]
 [ 3  4  5  6  7]]


In [11]:
print(simple_array.resize(3,5))

None


In [13]:
# a new shape to array without changing its data 
simple_array = np.arange(0,9).reshape(3,3)
simple_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# dimensions are automatically calculated when you use -1
sample_array = np.arange(0,9)
print(sample_array)
x = sample_array.reshape(3,-1)
print(x)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
# transpose of matrix i.e convert column into row
x.T



array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [26]:
# adding elements at the end of the array
y = np.append(sample_array, [10,11])
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [41]:
z = np.insert(y,8,9)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9,  8, 10, 11])

In [42]:
z = np.delete(sample_array,[8])
z

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
z

array([0, 1, 2, 3, 4, 5, 6, 7])

## split /join /stack Arrays

# np.r()-Arrange arrays row-wise
# np.c_()- Arrange arrays column-wise
# np.concatenate() - Concatentate two arrays
# np.hstack() - stack arrays horizontally
# np.vstack() -stack arrays vertically


In [5]:
import numpy as np
# create 2d arrays
array1 = np.arange(9).reshape(3,3)
array2 = np.arange(12).reshape(3,4)

print(array1)
print("\n")
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:

# concatenate 
# print(np.concatenate((array1,array2)))
# will throw an error due to improper dimension

array3 = np.arange(9,18).reshape(3, 3)
print(np.concatenate((array1, array3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [13]:
# stack the array elements horizonatally
np.hstack((array1, array3))

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [14]:
# stack array vertically 
np.vstack((array1, array3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [17]:
# stack array row-wise
print( np.r_[array1,array3])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [18]:
# stack arrays column wise
print(np.c_[array1,array3])

[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


In [24]:
# applying the mathematical operations

sample_array = np.arange(10,20)

print(np.exp(sample_array))
print("\n")
print(np.sin(sample_array))
print("\n")
print(np.cos(sample_array))

[2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
 1.20260428e+06 3.26901737e+06 8.88611052e+06 2.41549528e+07
 6.56599691e+07 1.78482301e+08]


[-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784
 -0.28790332 -0.96139749 -0.75098725  0.14987721]


[-0.83907153  0.0044257   0.84385396  0.90744678  0.13673722 -0.75968791
 -0.95765948 -0.27516334  0.66031671  0.98870462]


In [26]:
# execute a function in non -numpy way
non_numpy = [(x**2+2*x+3) for x in sample_array]
print(non_numpy)

[123, 146, 171, 198, 227, 258, 291, 326, 363, 402]


# linear algebra operations
## np.linalg.inv:inverse of matrix
## np.linalg.det: determinant of a matrix
## np.linalg.eig: Eigenvalues and eigenvectors of a matrix
## np.dot(a,b): dot product of two matrices