# structure of arrays

## .how to find out details of the arrays:
## .dtype:finds data type of array
## .shape: shows shape of array(n*m)
## .itemsize: Memory used by each array elements in bytes
## .ndim: Number of axes(or dimensions)

In [2]:
import numpy as np
# generate an array (5 *5)
# array1 = np.ones((5,5))
array1 = np.ones((5,5),dtype= int)
array1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
# Find dtype, shape, itemsize and ndim of array1
print(array1.dtype)
print(array1.shape)
print(array1.itemsize)
print(array1.ndim)


int32
(5, 5)
4
2


In [9]:
# creating the 3 d array difficult to print it
# reshape() simple reshape a 1-D array
array_3d = np.arange(12).reshape(2,3,2)
print(array_3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [6]:
# creating a 3d array different to print it
# reshape() simply reshape a 1-d array
array_3d = np.arange(24).reshape(6,4,1)
print(array_3d)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


# indexing, subsetting, slicing and iterating through arrays

In [7]:
# indexing and slicing and iterrating through arrays
array1d = np.arange(5)
print(array1d)

[0 1 2 3 4]


In [15]:
# access from the indexig
array1d[2]
# array1d[2:3] 

2

In [18]:
array1d[2:4]

array([2, 3])

In [20]:
array1d[[2,3,4]]

array([2, 3, 4])

In [21]:
# subset with an increment of 2
print(array1d[0::2])

[0 2 4]


In [22]:
# iterations also similar to list
for i in array1d:
    print(i*2)

0
2
4
6
8


In [27]:
# 2 d array accessing
array2d = np.array([[1,2,3,4],[5,6,7, 8],[9,10,11, 12]])
print(array2d)

print(array2d.ndim)
print(array2d[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
7


In [35]:
print(array2d[2,:])
# [ 9 10 11 12]
# slicing row
print(array2d[:,1])
# [ 2  6 10]
# # all row second column


print(array2d[:,:2])
# all the row and all column till second column 
# [[ 1  2]
#  [ 5  6]
#  [ 9 10]]


[ 9 10 11 12]
[ 2  6 10]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [36]:
print(array2d[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
print(array2d[:2,:])

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
print(array2d[2,:])
print(array2d[:,:2])

[ 9 10 11 12]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [42]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Slice along both dimensions
sliced = arr[0:2, 1:3]
print(sliced)


[[2 3]
 [5 6]]


In this example, arr[0:2, 1:3] selects a subset of the original array along both dimensions. The first slice object 0:2 specifies the rows to include (rows 0 and 1), and the second slice object 1:3 specifies the columns to include (columns 1 and 2). The resulting sliced array contains the values 2, 3, 5, 

In [44]:
# iterating over array (row wise and columnwise)
for column in array2d:
    print(column)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


# Execute speed in Numpy and standard Python 