In [7]:
# crate 1-d array using list/tuple
# use np.array
import numpy as np

fromList_to_1dArray = np.array([10,20,30,40,50])
fromTupleto_1dArray = np.array((1,2,3,4,5))

print(type(fromList_to_1dArray))
print(fromList_to_1dArray)

print(type(fromTupleto_1dArray))
print(fromTupleto_1dArray)

<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [9]:
# 2d array creation using two lists
fromList_to_2dArray = np.array([[0,1,2,3,4], [5,6,7,8,9]])
print(fromList_to_2dArray)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
# axis = 0 represent rows(Axis 0 is running vertically downwards across the row)
# axis =1 represents columns(Axis 1 is running from left to right across the columns)



In [20]:
num_list1 = [1,2,3,4,5,6,7,8,9]
num_list2 = [10,11,12,13,14,15,16,17,18,19]

sum_list = list(map(lambda x, y: x+y, num_list1, num_list2))
print(sum_list)

[11, 13, 15, 17, 19, 21, 23, 25, 27]


In [25]:
# use numpy arrays
# 1d array

np_list1 = np.array([1,2,3,4,5,6,7,8,9])
np_list2 = np.array([10,11,12,13,14,15,16,17,18,19])

np_sumList = num_list1+num_list2
print(np_sumList)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [26]:
# create array of fixed size
# from list

array_from_list = np.array([1,2,3,4,5])
array_from_list2 = np.array([1,2,3,4,5],dtype=float)
# from tuple
array_from_tuple = np.array((0,6,7,8,9))

print(array_from_list)
print(array_from_list2)
print(array_from_tuple)


[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[0 6 7 8 9]


In [27]:
# condition statement as an argumnet to np.array()

array_from_list3 = array_from_list >=2
print(array_from_list3)

[False  True  True  True  True]


In [28]:
# how to fetch the actual elements
array_from_list[array_from_list3]

array([2, 3, 4, 5])

In [31]:
# 2d Array
array1 = np.array([[0,1,2,3],[4,5,6,7]])
print(array1)

array2 = np.array([[10,11,12,13],[14,15,16,17]])
array2

[[0 1 2 3]
 [4 5 6 7]]


array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [32]:
array2 -array1

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [33]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

# how to initialize np arrays when size is known

## function that are used to do so are:

np.arrange():array creation with defined increments
np.zeros():array of 0s
np.ones():array of 1s
np.random.random():array of random numbers
np.random.randint():random array of integers within a particular range
np.linspace():array of fixed length
np.full():constant array of any number 'n'
np.eye():identity matrix array
np.title(): array is going to created may times

In [45]:

# np.arrange()
# range()
incrmnt = np.arange(1, 15,2)
incrmnt


array([ 1,  3,  5,  7,  9, 11, 13])

In [49]:
decrmnt = np.arange(50, 15,-2)
decrmnt

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16])

In [50]:
# zero intialization
np.zeros(5)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
# ones initialization
np.ones(3)
np.ones((3,3))
np.ones((3,3), dtype= int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
# random numbers array
np.random.random([4,4])

array([[0.80415816, 0.19534149, 0.64649594, 0.59954218],
       [0.97966405, 0.87725101, 0.89946114, 0.00287314],
       [0.57591729, 0.34653249, 0.22264148, 0.91830427],
       [0.75852062, 0.28793644, 0.55848725, 0.11311287]])

In [55]:
# creating a 3*3 random array of integers ranging from 0 to 9
np.random.randint(1,10,(3,3))

array([[3, 1, 1],
       [1, 8, 5],
       [5, 8, 1]])

In [57]:
# np.full -defult data type int
np.full(2,6)
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [58]:
# identity matrix
i_matrix = np.eye(5, dtype = int)
i_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [61]:
# np.linspace
#  length known , steps size unknown
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [67]:
# repeating array for the number of times - defult data type is int
import numpy as np

# Example 1
array1 = np.array([5, 4, 3])
array2 = np.tile(array1, 5)
print(array2)

# Output: [5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]

# Example 2
array3 = np.tile(array1, (4, 5))
print(array3)

# Output:
# [[5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]
#  [5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]
#  [5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]
#  [5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]]


[5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]
[[5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]
 [5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]
 [5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]
 [5 4 3 5 4 3 5 4 3 5 4 3 5 4 3]]
